development:
  adapter: postgresql
  database: bbyidx_dev
  template: template0  # fixes database encoding errors in newer versions of PostgreSQL
  min_messages: info

test:
  adapter: postgresql
  database: bbyidx_test
  template: template0  # fixes database encoding errors in newer versions of PostgreSQL
  timeout: 5000
  min_messages: warning
